### ISSUE TITLE
Top notification bar

### ISSUE THREAD

**Issue by vdcrea** [bpierre/lang_french#4]
Hi Nicolas or Pierre, I have french lang installed but it seems the top bar is not translated, I don't understand why because I see the right translation here for example https://github.com/bpierre/lang_french/blob/master/lang/lang.fr.php#L539
Any idea about how I can fix it?

**Comment by nitriques** [comment]
Fixed and released in `1.4.0`.

Format string sometimes changes in the core and this must be reflected in the lang dictionary as well.

**Comment by vdcrea** [comment]
Thanks Nicolas ! And happy new year :-)
